# Site settings
title: Politics Geek
email: paul@xk7.net
description: > # this means to ignore newlines until "baseurl:"
  UK Political Commentary
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.politicsgeek.co.uk" # the base hostname & protocol for your site
twitter_username: pwaring

permalink: /:year/:month/:day/:title/
#paginate: 10

# Build settings
markdown: kramdown
destination: ./output

# Gems
#gems: [jekyll-paginate]
